"""pharma vertical fields: territories, products, entity type, credit, dnd

Revision ID: 1a2a93264344
Revises: 6692e294096a
Create Date: 2026-08-14 23:43:38.378128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1a2a93264344'
down_revision: Union[str, None] = '6692e294096a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

entity_type_enum = postgresql.ENUM("doctor", "chemist", "stockist", "hospital", "other", name="entity_type")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    entity_type_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_table('territories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Enum('region', 'zone', 'area', 'beat', name='territory_level'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['territories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_territories_organization_id'), 'territories', ['organization_id'], unique=False)
    op.add_column('call_logs', sa.Column('order_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('call_logs', sa.Column('product_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'call_logs', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.add_column('leads', sa.Column('entity_type', postgresql.ENUM('doctor', 'chemist', 'stockist', 'hospital', 'other', name='entity_type', create_type=False), nullable=False, server_default='other'))
    op.add_column('leads', sa.Column('drug_license_number', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('specialty', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('territory_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('product_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('leads', sa.Column('outstanding_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('leads', sa.Column('dnd', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_leads_territory_id'), 'leads', ['territory_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'territories', ['territory_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('territory_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'territories', ['territory_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'territory_id')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_territory_id'), table_name='leads')
    op.drop_column('leads', 'dnd')
    op.drop_column('leads', 'outstanding_amount')
    op.drop_column('leads', 'credit_limit')
    op.drop_column('leads', 'product_id')
    op.drop_column('leads', 'territory_id')
    op.drop_column('leads', 'specialty')
    op.drop_column('leads', 'drug_license_number')
    op.drop_column('leads', 'entity_type')
    op.drop_constraint(None, 'call_logs', type_='foreignkey')
    op.drop_column('call_logs', 'product_id')
    op.drop_column('call_logs', 'order_value')
    op.drop_index(op.f('ix_territories_organization_id'), table_name='territories')
    op.drop_table('territories')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_table('products')
    entity_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
