"""add next_follow_up_at to leads and call_logs

Revision ID: 46fd2645ce7b
Revises: c5b7c13f4034
Create Date: 2026-08-15 14:06:09.383546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fd2645ce7b'
down_revision: Union[str, None] = 'c5b7c13f4034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_logs', sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_leads_next_follow_up_at'), 'leads', ['next_follow_up_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_next_follow_up_at'), table_name='leads')
    op.drop_column('leads', 'next_follow_up_at')
    op.drop_column('call_logs', 'next_follow_up_at')
    # ### end Alembic commands ###
