"""add lead integrations and justdial source

Revision ID: 616aac040307
Revises: c1a6455ed4d9
Create Date: 2026-08-15 22:49:51.518022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616aac040307'
down_revision: Union[str, None] = 'c1a6455ed4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic autogenerate never detects new enum *values*, only new types — this
    # has to be written by hand. On PG 12+ ADD VALUE is allowed inside a
    # transaction as long as the value isn't also *used* in that transaction
    # (we only add it here). IF NOT EXISTS keeps the migration re-runnable.
    op.execute("ALTER TYPE lead_source ADD VALUE IF NOT EXISTS 'justdial'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('indiamart', 'justdial', name='integration_provider'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('disconnected', 'active', 'error', name='integration_status'), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('webhook_secret', sa.String(length=64), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('total_imported', sa.Integer(), nullable=False),
    sa.Column('total_duplicates', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'provider', name='uq_integration_org_provider')
    )
    op.create_index(op.f('ix_lead_integrations_organization_id'), 'lead_integrations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lead_integrations_webhook_secret'), 'lead_integrations', ['webhook_secret'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_integrations_webhook_secret'), table_name='lead_integrations')
    op.drop_index(op.f('ix_lead_integrations_organization_id'), table_name='lead_integrations')
    op.drop_table('lead_integrations')
    # ### end Alembic commands ###

    # Postgres has no "ALTER TYPE ... DROP VALUE". Removing 'justdial' would mean
    # recreating lead_source and rewriting every dependent column, which risks
    # real lead data for no benefit. The unused value is left in place.
    op.execute("DROP TYPE IF EXISTS integration_status")
    op.execute("DROP TYPE IF EXISTS integration_provider")
