"""remove territory hierarchy, add state and city fields

Revision ID: c1a6455ed4d9
Revises: 46fd2645ce7b
Create Date: 2026-08-15 16:22:57.587135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1a6455ed4d9'
down_revision: Union[str, None] = '46fd2645ce7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

territory_level_enum = postgresql.ENUM('region', 'zone', 'area', 'beat', name='territory_level')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('leads_territory_id_fkey', 'leads', type_='foreignkey')
    op.drop_constraint('users_territory_id_fkey', 'users', type_='foreignkey')
    op.drop_index('ix_territories_organization_id', table_name='territories')
    op.drop_table('territories')
    territory_level_enum.drop(op.get_bind(), checkfirst=True)
    op.add_column('leads', sa.Column('state', sa.String(length=100), nullable=True))
    op.drop_index('ix_leads_territory_id', table_name='leads')
    op.create_index(op.f('ix_leads_city'), 'leads', ['city'], unique=False)
    op.drop_column('leads', 'territory_id')
    op.add_column('users', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.drop_column('users', 'territory_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('territory_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_territory_id_fkey', 'users', 'territories', ['territory_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'city')
    op.drop_column('users', 'state')
    op.add_column('leads', sa.Column('territory_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('leads_territory_id_fkey', 'leads', 'territories', ['territory_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_leads_city'), table_name='leads')
    op.create_index('ix_leads_territory_id', 'leads', ['territory_id'], unique=False)
    op.drop_column('leads', 'state')
    op.create_table('territories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('level', postgresql.ENUM('region', 'zone', 'area', 'beat', name='territory_level'), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='territories_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['territories.id'], name='territories_parent_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='territories_pkey')
    )
    op.create_index('ix_territories_organization_id', 'territories', ['organization_id'], unique=False)
    # ### end Alembic commands ###
