"""replace lead entity_type with category

Revision ID: c5b7c13f4034
Revises: 1a2a93264344
Create Date: 2026-08-15 13:15:06.358542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5b7c13f4034'
down_revision: Union[str, None] = '1a2a93264344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

lead_category_enum = postgresql.ENUM(
    "pharmaceutical", "ayurvedic", "homeopathic", "nutraceutical", "generic", "other", name="lead_category"
)
entity_type_enum = postgresql.ENUM("doctor", "chemist", "stockist", "hospital", "other", name="entity_type")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    lead_category_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'leads',
        sa.Column(
            'category',
            postgresql.ENUM(
                'pharmaceutical', 'ayurvedic', 'homeopathic', 'nutraceutical', 'generic', 'other',
                name='lead_category', create_type=False,
            ),
            nullable=False,
            server_default='other',
        ),
    )
    op.drop_column('leads', 'entity_type')
    entity_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    entity_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'leads',
        sa.Column(
            'entity_type',
            postgresql.ENUM('doctor', 'chemist', 'stockist', 'hospital', 'other', name='entity_type', create_type=False),
            server_default='other',
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column('leads', 'category')
    lead_category_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
